# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'menu.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(800, 800))
        MainWindow.setMaximumSize(QtCore.QSize(800, 800))
        MainWindow.setStyleSheet("background-color: rgb(255, 228, 21);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(150, 30, 501, 131))
        font = QtGui.QFont()
        font.setFamily("Freehand521 BT")
        font.setPointSize(28)
        self.label.setFont(font)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.irparaSoma = QtWidgets.QPushButton(self.centralwidget)
        self.irparaSoma.setGeometry(QtCore.QRect(70, 240, 161, 91))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.irparaSoma.setFont(font)
        self.irparaSoma.setStyleSheet("color: rgb(255, 255, 255);\n"
"alternate-background-color: rgb(0, 0, 0);\n"
"border-color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 90, 80);")
        self.irparaSoma.setObjectName("irparaSoma")
        self.irparaSubtra = QtWidgets.QPushButton(self.centralwidget)
        self.irparaSubtra.setGeometry(QtCore.QRect(310, 240, 161, 91))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(16)
        self.irparaSubtra.setFont(font)
        self.irparaSubtra.setStyleSheet("color: rgb(255, 255, 255);\n"
"alternate-background-color: rgb(0, 0, 0);\n"
"border-color: rgb(0, 0, 0);\n"
"background-color: rgb(170, 170, 0);")
        self.irparaSubtra.setObjectName("irparaSubtra")
        self.irparaMulti = QtWidgets.QPushButton(self.centralwidget)
        self.irparaMulti.setGeometry(QtCore.QRect(550, 240, 161, 91))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.irparaMulti.setFont(font)
        self.irparaMulti.setStyleSheet("color: rgb(255, 255, 255);\n"
"alternate-background-color: rgb(0, 0, 0);\n"
"border-color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 85, 255);")
        self.irparaMulti.setObjectName("irparaMulti")
        self.irparaDivi = QtWidgets.QPushButton(self.centralwidget)
        self.irparaDivi.setGeometry(QtCore.QRect(70, 400, 161, 91))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(16)
        self.irparaDivi.setFont(font)
        self.irparaDivi.setStyleSheet("color: rgb(255, 255, 255);\n"
"alternate-background-color: rgb(0, 0, 0);\n"
"border-color: rgb(0, 0, 0);\n"
"\n"
"background-color: rgb(0, 170, 255);")
        self.irparaDivi.setObjectName("irparaDivi")
        self.irparaEqui1 = QtWidgets.QPushButton(self.centralwidget)
        self.irparaEqui1.setGeometry(QtCore.QRect(310, 400, 161, 91))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.irparaEqui1.setFont(font)
        self.irparaEqui1.setStyleSheet("color: rgb(255, 255, 255);\n"
"alternate-background-color: rgb(0, 0, 0);\n"
"border-color: rgb(0, 0, 0);\n"
"background-color: rgb(85, 0, 0);")
        self.irparaEqui1.setObjectName("irparaEqui1")
        self.embreve = QtWidgets.QPushButton(self.centralwidget)
        self.embreve.setGeometry(QtCore.QRect(550, 400, 161, 91))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.embreve.setFont(font)
        self.embreve.setStyleSheet("color: rgb(255, 255, 255);\n"
"alternate-background-color: rgb(0, 0, 0);\n"
"border-color: rgb(0, 0, 0);\n"
"background-color: rgb(0, 0, 0);")
        self.embreve.setObjectName("embreve")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Matematica Para Todos - Inicio"))
        self.label.setText(_translate("MainWindow", "Matemática Para Todos!"))
        self.irparaSoma.setText(_translate("MainWindow", "+  SOMA +"))
        self.irparaSubtra.setText(_translate("MainWindow", "- SUBTRAÇÃO -"))
        self.irparaMulti.setText(_translate("MainWindow", "X MULTIPLICAÇÃO X "))
        self.irparaDivi.setText(_translate("MainWindow", "÷ DIVISÃO ÷ "))
        self.irparaEqui1.setText(_translate("MainWindow", "EQUAÇÃO DE 1º GRAU"))
        self.embreve.setText(_translate("MainWindow", "EM BREVE..."))
